language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g yarn typescript ts-node mocha protractor
install:
  - cd api-service/webapp-demo
  - yarn install
  - cd ../../
  - cd api-service/api-server
  - yarn install
  - cd ../../
script:
  - cd api-service/webapp-demo
  - yarn install
  - cd ../../
  - cd api-service/api-server
  - yarn run test --watch false
  - cd ../../
